export const USER_ROLES = [
  "PRODUCER", // Productor Rural
  "OPERATOR", // Comprador/Operador
  "MUNICIPALITY", // Municipio/Institución
  "TERRITORIAL_MANAGER", // Gestor Territorial
  "ADMIN" // Administrador AGRORED
] as const;

export type UserRole = typeof USER_ROLES[number];

export const PERMISSIONS = {
  CREATE_AUCTION: "CREATE_AUCTION",
  BID_ON_AUCTION: "BID_ON_AUCTION",
  ACCEPT_DUTCH_PRICE: "ACCEPT_DUTCH_PRICE",
  VIEW_AUCTION: "VIEW_AUCTION",
  VIEW_AUCTION_REPORTS: "VIEW_AUCTION_REPORTS",
  AUDIT_AUCTION: "AUDIT_AUCTION",
  VIEW_REPORTS: "VIEW_REPORTS",
  MANAGE_USERS: "MANAGE_USERS",
  AUDIT_SYSTEM: "AUDIT_SYSTEM"
} as const;

type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  PRODUCER: [PERMISSIONS.CREATE_AUCTION, PERMISSIONS.VIEW_AUCTION],
  OPERATOR: [PERMISSIONS.BID_ON_AUCTION, PERMISSIONS.ACCEPT_DUTCH_PRICE, PERMISSIONS.VIEW_AUCTION],
  MUNICIPALITY: [PERMISSIONS.BID_ON_AUCTION, PERMISSIONS.ACCEPT_DUTCH_PRICE, PERMISSIONS.VIEW_AUCTION, PERMISSIONS.VIEW_AUCTION_REPORTS, PERMISSIONS.VIEW_REPORTS],
  TERRITORIAL_MANAGER: [PERMISSIONS.VIEW_AUCTION, PERMISSIONS.VIEW_AUCTION_REPORTS, PERMISSIONS.VIEW_REPORTS],
  ADMIN: [PERMISSIONS.MANAGE_USERS, PERMISSIONS.AUDIT_SYSTEM, PERMISSIONS.AUDIT_AUCTION]
};

export const MODULE_ACCESS: Record<string, UserRole[]> = {
  "analytics-service": ["ADMIN", "TERRITORIAL_MANAGER"],
  "api-gateway": ["ADMIN"],
  "automation-service": ["ADMIN", "OPERATOR"],
  "demand-service": ["OPERATOR", "MUNICIPALITY"],
  "incident-service": ["MUNICIPALITY", "TERRITORIAL_MANAGER"],
  "inventory-service": ["OPERATOR", "MUNICIPALITY"],
  "logistics-service": ["OPERATOR", "MUNICIPALITY", "TERRITORIAL_MANAGER"],
  "ml-service": ["ADMIN"],
  "notification-service": ["ADMIN", "OPERATOR"],
  "offer-service": ["OPERATOR", "MUNICIPALITY"],
  "producer-service": ["PRODUCER", "ADMIN"],
  "rescue-service": ["PRODUCER", "MUNICIPALITY"],
  "auction-service": ["PRODUCER", "OPERATOR", "MUNICIPALITY", "TERRITORIAL_MANAGER", "ADMIN"],
  "user-service": ["ADMIN"],
  "web-dashboard": ["ADMIN", "OPERATOR", "MUNICIPALITY", "TERRITORIAL_MANAGER", "PRODUCER"]
};

