// Test credentials — generated by scripts/seed_rionegro_pilot.ts (tenant RIONEGRO)
// Pattern: email = role.{role}.rionegro@agrored.co  |  password = Role@RIONEGRO{r+1}!
// Override via env vars for CI. Mirrors tests/e2e/fixtures/users.ts (tenant BOGOTA).

export const RIONEGRO_USERS = {
  admin: {
    email: process.env.E2E_RIONEGRO_ADMIN_EMAIL ?? "role.admin_municipal.rionegro@agrored.co",
    password: process.env.E2E_RIONEGRO_ADMIN_PASS ?? "Role@RIONEGRO1!",
    role: "admin_municipal",
  },
  producer: {
    email: process.env.E2E_RIONEGRO_PRODUCER_EMAIL ?? "role.producer.rionegro@agrored.co",
    password: process.env.E2E_RIONEGRO_PRODUCER_PASS ?? "Role@RIONEGRO2!",
    role: "producer",
  },
  // Second producer account — distinct from `producer` above, used to verify that a
  // producer cannot see/edit another producer's offers within the same tenant.
  producer2: {
    email: process.env.E2E_RIONEGRO_PRODUCER2_EMAIL ?? "role.producer2.rionegro@agrored.co",
    password: process.env.E2E_RIONEGRO_PRODUCER2_PASS ?? "Role@RIONEGRO2B!",
    role: "producer",
  },
  supermarket: {
    email: process.env.E2E_RIONEGRO_SUPERMARKET_EMAIL ?? "role.supermarket.rionegro@agrored.co",
    password: process.env.E2E_RIONEGRO_SUPERMARKET_PASS ?? "Role@RIONEGRO3!",
    role: "supermarket",
  },
  logistics: {
    email: process.env.E2E_RIONEGRO_LOGISTICS_EMAIL ?? "role.logistics_operator.rionegro@agrored.co",
    password: process.env.E2E_RIONEGRO_LOGISTICS_PASS ?? "Role@RIONEGRO4!",
    role: "logistics_operator",
  },
  analyst: {
    email: process.env.E2E_RIONEGRO_ANALYST_EMAIL ?? "role.territorial_analyst.rionegro@agrored.co",
    password: process.env.E2E_RIONEGRO_ANALYST_PASS ?? "Role@RIONEGRO5!",
    role: "territorial_analyst",
  },
  kitchen: {
    email: process.env.E2E_RIONEGRO_KITCHEN_EMAIL ?? "role.community_kitchen.rionegro@agrored.co",
    password: process.env.E2E_RIONEGRO_KITCHEN_PASS ?? "Role@RIONEGRO6!",
    role: "community_kitchen",
  },
  monitoring: {
    email: process.env.E2E_RIONEGRO_MONITORING_EMAIL ?? "role.monitoring_agent.rionegro@agrored.co",
    password: process.env.E2E_RIONEGRO_MONITORING_PASS ?? "Role@RIONEGRO7!",
    role: "monitoring_agent",
  },
} as const;

export const RIONEGRO_TENANT_CODE = "RIONEGRO";
