// Test credentials — generated by scripts/seed_oriente_antioqueno_pilot.ts.
// Pattern: email = role.{role}.{tenantcode}@agrored.co | password = Role@{TENANTCODE}{r+1}!
// Same pattern as fixtures/users.ts (BOGOTA) and fixtures/users.rionegro.ts (RIONEGRO),
// generalized here for the 8 remaining Oriente Antioqueño municipios.

export const ORIENTE_ANTIOQUENO_MUNICIPIOS = [
  { code: "MARINILLA", name: "Marinilla" },
  { code: "ELCARMEN", name: "El Carmen de Viboral" },
  { code: "GUARNE", name: "Guarne" },
  { code: "LACEJA", name: "La Ceja" },
  { code: "ELRETIRO", name: "El Retiro" },
  { code: "SANVICENTE", name: "San Vicente Ferrer" },
  { code: "SANTUARIO", name: "El Santuario" },
  { code: "PENOL", name: "El Peñol" },
] as const;

const ROLES = [
  "admin_municipal", "producer", "supermarket", "logistics_operator",
  "territorial_analyst", "community_kitchen", "monitoring_agent",
] as const;

export function usersForTenant(tenantCode: string) {
  const lower = tenantCode.toLowerCase();
  const byRole: Record<string, { email: string; password: string; role: string }> = {};
  ROLES.forEach((role, i) => {
    byRole[role] = {
      email: `role.${role}.${lower}@agrored.co`,
      password: `Role@${tenantCode}${i + 1}!`,
      role,
    };
  });
  return {
    admin: byRole.admin_municipal,
    producer: byRole.producer,
    producer2: { email: `role.producer2.${lower}@agrored.co`, password: `Role@${tenantCode}2B!`, role: "producer" },
    supermarket: byRole.supermarket,
    logistics: byRole.logistics_operator,
    analyst: byRole.territorial_analyst,
    kitchen: byRole.community_kitchen,
    monitoring: byRole.monitoring_agent,
  };
}
