// Test credentials — generated by seed_expanded.ts (tenant BOGOTA, r index per role)
// Pattern: email = role.{role}.bogota@agrored.co  |  password = Role@BOGOTA{r+1}!
// Override via env vars for CI.

export const USERS = {
  admin: {
    email: process.env.E2E_ADMIN_EMAIL ?? "role.admin_municipal.bogota@agrored.co",
    password: process.env.E2E_ADMIN_PASS ?? "Role@BOGOTA1!",
    role: "admin_municipal",
  },
  producer: {
    email: process.env.E2E_PRODUCER_EMAIL ?? "role.producer.bogota@agrored.co",
    password: process.env.E2E_PRODUCER_PASS ?? "Role@BOGOTA2!",
    role: "producer",
  },
  supermarket: {
    email: process.env.E2E_SUPERMARKET_EMAIL ?? "role.supermarket.bogota@agrored.co",
    password: process.env.E2E_SUPERMARKET_PASS ?? "Role@BOGOTA3!",
    role: "supermarket",
  },
  logistics: {
    email: process.env.E2E_LOGISTICS_EMAIL ?? "role.logistics_operator.bogota@agrored.co",
    password: process.env.E2E_LOGISTICS_PASS ?? "Role@BOGOTA4!",
    role: "logistics_operator",
  },
  analyst: {
    email: process.env.E2E_ANALYST_EMAIL ?? "role.territorial_analyst.bogota@agrored.co",
    password: process.env.E2E_ANALYST_PASS ?? "Role@BOGOTA5!",
    role: "territorial_analyst",
  },
  kitchen: {
    email: process.env.E2E_KITCHEN_EMAIL ?? "role.community_kitchen.bogota@agrored.co",
    password: process.env.E2E_KITCHEN_PASS ?? "Role@BOGOTA6!",
    role: "community_kitchen",
  },
  monitoring: {
    email: process.env.E2E_MONITORING_EMAIL ?? "role.monitoring_agent.bogota@agrored.co",
    password: process.env.E2E_MONITORING_PASS ?? "Role@BOGOTA7!",
    role: "monitoring_agent",
  },
} as const;

export const API_URL = process.env.E2E_API_URL ?? "http://localhost:8082";
