// ── IRAT (Índice de Riesgo Alimentario Territorial) ──

export interface IratScore {
  tenantId: string;
  tenantCode: string;
  tenantName: string;
  totalOffers: number;
  totalOfferQuantity: number;
  openDemands: number;
  totalDemandQuantity: number;
  totalBeneficiaries: number;
  scheduledRescues: number;
  totalRescuedQuantity: number;
  openIncidents: number;
  criticalIncidents: number;
  activeLogistics: number;
  activePrograms: number;
  programCoverage: number;
  iratScore: number;  // 0-100 (higher = higher risk)
}

// ── Food Programs ──

export interface FoodProgram {
  id: string;
  tenantId: string;
  name: string;
  programType: string;
  description: string | null;
  targetPopulation: number;
  currentCoverage: number;
  budgetAllocated: number;
  budgetExecuted: number;
  responsibleName: string | null;
  responsibleEmail: string | null;
  municipalityName: string;
  status: string;
  startsAt: string | null;
  endsAt: string | null;
  metadata: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

export interface FoodProgramCreateCommand {
  tenantId: string;
  name: string;
  programType: string;
  description?: string;
  targetPopulation?: number;
  budgetAllocated?: number;
  responsibleName?: string;
  responsibleEmail?: string;
  municipalityName: string;
  startsAt?: string;
  endsAt?: string;
}

// ── Beneficiaries ──

export interface Beneficiary {
  id: string;
  tenantId: string;
  programId: string | null;
  fullName: string;
  documentId: string | null;
  documentType: string | null;
  age: number | null;
  gender: string | null;
  socioeconomicLevel: number | null;
  riskClassification: string | null;
  nutritionalStatus: string | null;
  municipalityName: string;
  zoneName: string | null;
  address: string | null;
  latitude: number | null;
  longitude: number | null;
  contactPhone: string | null;
  isActive: boolean;
  createdAt: Date;
}

export interface BeneficiaryCreateCommand {
  tenantId: string;
  programId?: string;
  fullName: string;
  documentId?: string;
  documentType?: string;
  age?: number;
  gender?: string;
  socioeconomicLevel?: number;
  riskClassification?: string;
  nutritionalStatus?: string;
  municipalityName: string;
  zoneName?: string;
  address?: string;
  latitude?: number;
  longitude?: number;
  contactPhone?: string;
}

// ── Institutional Alerts ──

export interface InstitutionalAlert {
  id: string;
  tenantId: string;
  alertType: string;
  severity: string;
  title: string;
  description: string;
  indicatorName: string | null;
  indicatorValue: number | null;
  thresholdValue: number | null;
  zoneName: string | null;
  isAcknowledged: boolean;
  acknowledgedBy: string | null;
  acknowledgedAt: Date | null;
  autoGenerated: boolean;
  metadata: Record<string, unknown>;
  createdAt: Date;
}

// ── Coordination Tasks ──

export interface CoordinationTask {
  id: string;
  tenantId: string;
  actorType: string;
  actorName: string;
  taskDescription: string;
  assignedTo: string | null;
  status: string;
  priority: string;
  dueDate: string | null;
  completedAt: Date | null;
  notes: string | null;
  metadata: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
}

// ── Program Coverage view ──

export interface ProgramCoverage {
  tenantId: string;
  programId: string;
  programName: string;
  programType: string;
  targetPopulation: number;
  currentCoverage: number;
  coveragePct: number;
  budgetAllocated: number;
  budgetExecuted: number;
  budgetExecutionPct: number;
  municipalityName: string;
  status: string;
  totalDeliveries: number;
  totalDeliveredQuantity: number;
  enrolledBeneficiaries: number;
}

// ── Institutional Dashboard (aggregated) ──

export interface InstitutionalDashboard {
  irat: IratScore[];
  kpis: {
    avgIratScore: number;
    totalPopulationServed: number;
    totalFoodCoverage: number;
    totalTonsDistributed: number;
    totalFoodRescued: number;
    wasteAvoided: number;
    logisticsEfficiency: number;
    avgResponseTime: number;
  };
  alerts: InstitutionalAlert[];
  programCoverage: ProgramCoverage[];
  generatedAt: string;
}

// ── Spoilage / Merma ──

export const SPOILAGE_REASONS = ["expired", "temperature", "damaged", "contaminated", "overproduction", "other"] as const;
export type SpoilageReason = (typeof SPOILAGE_REASONS)[number];

export const SPOILAGE_STAGES = ["harvest", "storage", "transport", "distribution", "last_mile"] as const;
export type SpoilageStage = (typeof SPOILAGE_STAGES)[number];

export interface SpoilageRecord {
  id: string;
  tenantId: string;
  programId: string | null;
  logisticsOrderId: string | null;
  productName: string;
  category: string;
  quantityKg: number;
  spoilageKg: number;
  spoilageReason: SpoilageReason;
  stage: SpoilageStage;
  temperatureC: number | null;
  detectedAt: Date;
  detectedBy: string | null;
  locationName: string | null;
  latitude: number | null;
  longitude: number | null;
  notes: string | null;
  createdAt: Date;
}

export interface SpoilageCreateCommand {
  tenantId: string;
  programId?: string;
  logisticsOrderId?: string;
  productName: string;
  category?: string;
  quantityKg: number;
  spoilageKg: number;
  spoilageReason?: SpoilageReason;
  stage?: SpoilageStage;
  temperatureC?: number;
  detectedBy?: string;
  locationName?: string;
  latitude?: number;
  longitude?: number;
  notes?: string;
}

export interface SpoilageSummary {
  category: string;
  stage: string;
  spoilageReason: string;
  recordCount: number;
  totalQuantityKg: number;
  totalSpoilageKg: number;
  spoilageRatePct: number;
  avgTemperatureC: number | null;
  lastDetected: Date;
}
